// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace InfrastructureRequestApp.Data.Entities;

public partial class Request
{
    public Guid RequestId { get; set; }

    public string RequestType { get; set; }

    public string Description { get; set; }

    public string Urgency { get; set; }

    public string Note { get; set; }

    public string Status { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public Guid? AssignedTo { get; set; }

    public virtual User AssignedToNavigation { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual ICollection<RequestComment> RequestComments { get; set; } = new List<RequestComment>();
}