// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace InfrastructureRequestApp.Data.Entities;

public partial class RequestComment
{
    public Guid CommentId { get; set; }

    public Guid RequestId { get; set; }

    public string CommentText { get; set; }

    public Guid CommentedBy { get; set; }

    public DateTime CommentDate { get; set; }

    public virtual User CommentedByUser { get; set; }

    public virtual Request Request { get; set; }
}