// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace InfrastructureRequestApp.Data.Entities;

public partial class User
{
    public Guid UserId { get; set; }

    public string UserName { get; set; }

    public string PasswordHash { get; set; }

    public string FullName { get; set; }

    public string UserType { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual ICollection<Request> RequestAssignedToNavigations { get; set; } = new List<Request>();

    public virtual ICollection<RequestComment> RequestComments { get; set; } = new List<RequestComment>();

    public virtual ICollection<Request> RequestCreatedByNavigations { get; set; } = new List<Request>();
}